{{- if .Values.ingress.httpAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.authSecretName" . }}
type: Opaque
data:
  auth: {{ (htpasswd .Values.ingress.httpAuth.user .Values.ingress.httpAuth.password) | b64enc }}
{{- end -}}