apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend.fullname" . }}
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "frontend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "frontend.configmapName" . }}
                  key: db_host
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "frontend.configmapName" . }}
                  key: db_user
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "frontend.configmapName" . }}
                  key: db_name
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "frontend.secretName" . }}
                  key: db_password
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
